version: '3.4'

services:
  github-repo-api:
    image: github-repo-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
